chore: adds initial setup and build script for Apple Silicon
proj-clarity-esbmc/clara_esbmc pull request #20
Opened 2024-09-18 11:37 UTC by saad-s

* adds `apple_silicon_setup.sh`
* installs tools and dependencies
* builds from main branch

2024-09-20 11:44 UTC, mali-tintash requested changes

2024-09-20 11:44 UTC, mali-tintash commented on apple_silicon_setup.sh
> +  cmake .. -DENABLE_Z3=1 -DENABLE_SOLIDITY_FRONTEND=On -DENABLE_CLARITY_FRONTEND=On -DC2GOTO_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk ||
Add -DCMAKE_BUILD_TYPE=Debug as well plz

2024-09-23 05:42 UTC, saad-s commented on apple_silicon_setup.sh
> +  cmake .. -DENABLE_Z3=1 -DENABLE_SOLIDITY_FRONTEND=On -DENABLE_CLARITY_FRONTEND=On -DC2GOTO_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk ||
added

2024-09-23 07:35 UTC, mali-tintash approved these changes
LGTM

2024-09-23 07:36 UTC, merged