feat: adds var-get translation
proj-clarity-esbmc/clara_esbmc pull request #23
Opened 2024-09-25 09:44 UTC by saad-s

* adds template functions for primitives and sequences
* sets custom type properties for all literals

2024-10-01 13:13 UTC, mali-tintash requested changes

2024-10-01 13:13 UTC, mali-tintash commented on src/clarity-frontend/clarity_convert.cpp
> +      }
This is test code. We don't want it to be part of the main repo.

2024-10-01 13:13 UTC, mali-tintash commented on src/clarity-frontend/clarity_convert.cpp
> +      // functions like var-get and others which use kebab case
"mutton" kebab or "chicken" kebab ?

2024-10-01 13:13 UTC, mali-tintash commented on src/clarity-frontend/clarity_convert.cpp
>        // there is no need to translate size for list because there is no way to "get-size" of the list
I think we can remove this comment now since we are using the list size and translating it as well.

2024-10-01 13:13 UTC, mali-tintash commented on src/clarity-frontend/clarity_convert.cpp
> +    buff_inits = gen_address_of(buff_inits);
didn't we want to add "clarity_gen_typecast" here ? why "gen_address_of" ?

2024-10-01 13:13 UTC, mali-tintash commented on src/clarity-frontend/clarity_convert_literals.cpp
> +        nlohmann::json::array({"string-utf8", "string-utf8", width});
Can you test the utf-8 string value by assigning it like this please ?
`(define-data-var barfu (string-utf8 16) u"smile \u{1F600}")`

2024-10-01 13:32 UTC, saad-s commented on src/clarity-frontend/clarity_convert.cpp
> +            log_status("Parsing {} {} ", decl_decorator, identifier);
I think we should add some prettier rules...

2024-10-01 13:34 UTC, saad-s commented on src/clarity-frontend/clarity_convert.cpp
> +      }
got it. will remove before merge

2024-10-01 13:36 UTC, saad-s commented on src/clarity-frontend/clarity_convert.cpp
> +      if(std::size(expr_type) > 3) {
```
["list", "list", "2", ["bool", "bool", 1]] 
```
with nested type the size will be more than 3 otherwise 3

2024-10-01 13:36 UTC, saad-s commented on src/clarity-frontend/clarity_convert.cpp
> +      // functions like var-get and others which use kebab case
behari ...

2024-10-02 08:12 UTC, mali-tintash approved these changes

2024-10-02 08:12 UTC, mali-tintash commented on src/clarity-frontend/clarity_convert_literals.cpp
> +        nlohmann::json::array({"string-utf8", "string-utf8", width});
Tested. new changes should fix it.

2024-10-02 08:15 UTC, merged