feat: handles response data type and response as function return type
proj-clarity-esbmc/clara_esbmc pull request #25
Opened 2024-10-07 10:26 UTC by saad-s

* defines the symbol for response variable
* sets init value for response variable
* handles none as literal type ( handled as bool )
* fixes function return type

### NOTE: `clarity_convert.h` has changes on lines 93 & 106. Rest is auto formatting
### NOTE: This PR copies response structure handling from #21

2024-10-07 10:36 UTC, mali-tintash requested changes

2024-10-07 10:36 UTC, mali-tintash commented on src/clarity-frontend/clarity_convert.cpp
> +symbolt *clarity_convertert::add_response_symbol_table(
should it be "add_response_to_symbol_table" ?

2024-10-07 10:36 UTC, mali-tintash commented on src/clarity-frontend/clarity_convert.cpp
> +    get_type_description(nested_objtype[0], second_comp_type);
what value would this attain in case where a response can have both ok and err value ?

2024-10-07 11:18 UTC, saad-s commented on src/clarity-frontend/clarity_convert.cpp
> +    get_type_description(nested_objtype[0], second_comp_type);
Ok or err whichever is set by response will be set other will be gen_zero

2024-10-07 11:18 UTC, saad-s commented on src/clarity-frontend/clarity_convert.cpp
> +symbolt *clarity_convertert::add_response_symbol_table(
Yes.. will change it

2024-10-08 13:05 UTC, mali-tintash approved these changes

2024-10-08 13:06 UTC, merged