feat: handles multi statement clarity functions
proj-clarity-esbmc/clara_esbmc pull request #26
Opened 2024-10-10 09:05 UTC by saad-s

* covers functions with let and begin blocks
* handles multi expression function as code block
* updates return value handling for SingleStatement functions
* changes basic maths operations to multi-op

2024-10-10 10:44 UTC, mali-tintash requested changes
Left some comments

2024-10-10 10:44 UTC, mali-tintash commented on src/clarity-frontend/clarity_convert.cpp
> +      // TODO: ss -- fix me for codet vs code block with return statement
isn't this the fix ?

2024-10-10 11:40 UTC, saad-s commented on src/clarity-frontend/clarity_convert.cpp
> +      // TODO: ss -- fix me for codet vs code block with return statement
forgot to remove the comment. resolved.

2024-10-10 11:53 UTC, mali-tintash approved these changes

2024-10-10 19:49 UTC, saad-s commented on src/clarity-frontend/clarity_convert.cpp
> +      exprt assign_var_expr = symbol_exprt(returned_sym.id, returned_sym.type);
done, please review `creat_variable_symbol()`

2024-10-10 19:49 UTC, saad-s commented on src/clarity-frontend/clarity_grammar.cpp
> +    "||",  "+=", "-=", "*=", "/=", "%=", "<<=", ">>=", "&=", "|=", "^=", "**"};
done. need to discus unary operators

2024-10-11 05:35 UTC, mali-tintash requested changes

2024-10-11 05:35 UTC, mali-tintash commented on src/clarity-frontend/clarity_convert.cpp
> +
this should reuse create_symbol. 
the only thing create symbol require is expr to get location. You are doing the same thing here.
to reduce the chances of missing something while creating symbols, let's retrofit create symbol inside "create_variable_symbol" and you can keep the line 5279 because that's specific to this function use case.

Regarding create decl, that's a good idea, but then you should rename the function to "create_temp_variable" and update the function comments to something liek "Create a temporary variable inside a function to store intermediate values"

Make sure to return that code_decl through reference params.

2024-10-11 05:35 UTC, mali-tintash commented on src/clarity-frontend/clarity_grammar.cpp
> +// TODO: ss -- think about secp* and sha utils of clarity
sha and other utils will be implemented in C template if needed. it's too complex to implement inside ESBMC.

2024-10-11 05:35 UTC, mali-tintash commented on src/clarity-frontend/clarity_grammar.cpp
> +// TODO: ss -- not and bit-not are unary operators
yes they are.

2024-10-11 05:35 UTC, mali-tintash commented on src/clarity-frontend/clarity_convert.cpp
> +      exprt assign_var_expr = symbol_exprt(returned_sym.id, returned_sym.type);
left comments.

2024-10-11 07:03 UTC, saad-s commented on src/clarity-frontend/clarity_convert.cpp
> +
create symbol will need default param for lvalue flag, it doesn't set it as is. But just tested and the code out is fine with create symbol. Adding it. 

And regarding decl I tried that earlier but wasn't able to return code_declt via reference params because of some contractor limitations, I guess. So it wasn't very clean.

2024-10-11 09:06 UTC, saad-s commented on src/clarity-frontend/clarity_grammar.cpp
> +// TODO: ss -- think about secp* and sha utils of clarity
got it

2024-10-11 09:06 UTC, saad-s commented on src/clarity-frontend/clarity_grammar.cpp
> +// TODO: ss -- not and bit-not are unary operators
it was just a pointer for me to handle it later

2024-10-11 09:18 UTC, merged