Update the grammar file for AST
proj-clarity-esbmc/clara_esbmc pull request #6
Opened 2024-08-16 10:04 UTC by mutahirtintash

2024-08-16 12:37 UTC, mali-tintash requested changes

2024-08-16 12:37 UTC, mali-tintash commented on docs/Pseudocode-for-Reading-AST-F3
> +                  "value" : ONLY FOR variable initializations --- Expression node for the variable initialization value.
"value" is duplicate. here at line 67 and on line 57

2024-08-16 12:37 UTC, mali-tintash commented on docs/Pseudocode-for-Reading-AST-F3
> +                           For trait_functions this object must be present to define the functions return_type
these three are defined above as well. is it duplicate ? or did you have something else in mind ?

2024-08-16 12:39 UTC, mutahirtintash commented on docs/Pseudocode-for-Reading-AST-F3
> +                           For trait_functions this object must be present to define the functions return_type
No in the previous AST it seemed like these lines looked like detailed explanations of fields, Ill move them

2024-08-20 05:43 UTC, mali-tintash approved these changes

2024-08-20 05:43 UTC, merged